apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: monitoring
  labels:
    app: alertmanager
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m

    route:
      receiver: "slack-notifications"
      group_by: ['alertname', 'severity']
      group_wait: 10s
      group_interval: 30s
      repeat_interval: 1h

    receivers:
    - name: "slack-notifications"
      slack_configs:
      - send_resolved: true
        api_url: "https://hooks.slack.com/services/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"
        channel: "#social"   
        title: |-
          [{{ .Status | toUpper }}] {{ .CommonLabels.alertname }}
        text: |-
          *Alert:* {{ .CommonLabels.alertname }}
          *Severity:* {{ .CommonLabels.severity }}
          *Description:* {{ .Annotations.description }}
          *Details:* {{ range .CommonLabels.SortedPairs }} • *{{ .Name }}:* {{ .Value }}
          {{ end }}