apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: fastapi-monitor
  namespace: monitoring
  labels:
    app: fastapi-app
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app: fastapi-app
  namespaceSelector:
    matchNames:
      - microservice
  endpoints:
    - port: http
      interval: 30s
      path: /metrics
      scheme: http
