apiVersion: v1
kind: Service
metadata:
  name: fastapi-app-service
  namespace: microservice
  labels:
    app: fastapi-app
spec:
  selector:
    app: fastapi-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP